#!/bin/bash

function do_the_job() {
  local sub=$1
  echo $sub
  cd $out_dir/$sub
  cp ./flair/$sub.flair_ro.nii.gz ./
  cp ./anat/$sub.anat_ro.nii.gz ./
  gzip -fd *.gz
  matlab -nodisplay -nodesktop -nosplash -nojvm -r "ps_LST_lga('./$sub.anat_ro.nii', './$sub.flair_ro.nii',$kappa, 1, 50, 0);exit"

}


out_dir="../20190801"
kappa=0.6 # default
N=3 # number of parallel processes

cd $out_dir
subs=($(ls -d S*))
#subs=( "SMART001" "SMART002")
echo ${subs[@]}

for s in ${subs[@]}; do
   ((i=i%N)); ((i++==0)) && wait
   do_the_job $s &
done
wait

exit 0
